# Generated by Django 2.1.2 on 2018-10-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='xinjie', max_length=16, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='', upload_to='static/img/blog/'),
        ),
    ]
